#!/bin/bash
# claude-review - AI-powered PR reviewer
# Bounty: $150 USD (https://github.com/claude-builders-bounty/claude-builders-bounty/issues/4)

set -e

PR_URL="${1:-}"

if [ -z "$PR_URL" ]; then
    echo "Usage: claude-review --pr https://github.com/owner/repo/pull/123"
    exit 1
fi

# Parse PR URL
REPO=$(echo "$PR_URL" | sed 's|https://github.com/||' | cut -d'/' -f1,2)
PR_NUM=$(echo "$PR_URL" | cut -d'/' -f7)

# Get PR data
PR_TITLE=$(gh pr view "$PR_NUM" --repo "$REPO" --json title --jq '.title')
PR_AUTHOR=$(gh pr view "$PR_NUM" --repo "$REPO" --json author --jq '.author.login')
PR_DIFF=$(gh pr diff "$PR_NUM" --repo "$REPO")

# Analyze with Claude
echo "Analyzing PR #$PR_NUM: $PR_TITLE"
echo "Author: $PR_AUTHOR"
echo ""

# Send to Claude API (requires ANTHROPIC_API_KEY)
REVIEW=$(claude --print "Review this PR diff and output structured Markdown:

$PR_DIFF

Output format:
## Summary
(2-3 sentences)

## Identified Risks
- Risk 1
- Risk 2

## Improvement Suggestions
- Suggestion 1
- Suggestion 2

## Confidence Score
Low / Medium / High

Be thorough and specific.")

echo "$REVIEW"
echo ""
echo "---"
echo "Generated by claude-review"
echo "PR: $PR_URL"