#!/bin/bash
# changelog-generator - Generate structured CHANGELOG from git history
# Bounty: $50 USD (https://github.com/claude-builders-bounty/claude-builders-bounty/issues/1)

set -e

REPO_PATH="${1:-.}"
FROM_DATE="${2:-$(git log --reverse --format=%ci | head -1 | cut -d' ' -f1)}"
TO_DATE="${3:-$(date +%Y-%m-%d)}"

cd "$REPO_PATH" 2>/dev/null || { echo "Error: Not a git repository"; exit 1; }

echo "# CHANGELOG"
echo ""
echo "All notable changes to this project will be documented in this file."
echo ""

# Get all tags sorted by date
TAGS=$(git tag --sort=-creatordate 2>/dev/null || echo "")

if [ -z "$TAGS" ]; then
    # No tags, generate by date range
    COMMITS=$(git log --since="$FROM_DATE" --until="$TO_DATE" --format="%H|%ci|%s|%an" --reverse)
else
    # Generate by tags
    for TAG in $TAGS; do
        TAG_DATE=$(git log -1 --format=%ci "$TAG" | cut -d' ' -f1)
        PREV_TAG=$(git tag --sort=-creatordate | grep -B1 "$TAG" | tail -1)
        
        if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --format="%H|%ci|%s|%an" "$TAG" --reverse)
        else
            COMMITS=$(git log "$PREV_TAG".."$TAG" --format="%H|%ci|%s|%an" --reverse)
        fi
        
        echo "## [$TAG] - $TAG_DATE"
        echo ""
        
        ADDED=""
        CHANGED=""
        FIXED=""
        REMOVED=""
        
        while IFS='|' read -r HASH DATE MSG AUTHOR; do
            MSG_LOWER=$(echo "$MSG" | tr '[:upper:]' '[:lower:]')
            
            if [[ "$MSG_LOWER" =~ ^(feat|add|feature) ]]; then
                ADDED="$ADDED\n- $MSG ($AUTHOR)"
            elif [[ "$MSG_LOWER" =~ ^(fix|bugfix) ]]; then
                FIXED="$FIXED\n- $MSG ($AUTHOR)"
            elif [[ "$MSG_LOWER" =~ ^(change|update|modify|refactor) ]]; then
                CHANGED="$CHANGED\n- $MSG ($AUTHOR)"
            elif [[ "$MSG_LOWER" =~ ^(remove|delete|drop) ]]; then
                REMOVED="$REMOVED\n- $MSG ($AUTHOR)"
            fi
        done <<< "$COMMITS"
        
        [ -n "$ADDED" ] && echo "### Added" && echo -e "$ADDED" && echo ""
        [ -n "$CHANGED" ] && echo "### Changed" && echo -e "$CHANGED" && echo ""
        [ -n "$FIXED" ] && echo "### Fixed" && echo -e "$FIXED" && echo ""
        [ -n "$REMOVED" ] && echo "### Removed" && echo -e "$REMOVED" && echo ""
    done
fi

echo "### Generated by changelog-generator"
echo "### $(date +%Y-%m-%d)"